from __future__ import annotations

import os

def get_samples_names_from_summms2_folder(ResultsFolder,
                                          ToReplace = 'mzML-ms2Summary.xlsx'):
    """
    Extract sample names from an ms2Topo summary-results folder.

    This reproduces the SamplesNames vector generated by JoiningSummMS2,
    without reading or joining the summary tables.

    Expected:
        ResultsFolder contains files ending in .xlsx.

    Example filename:
        Sample_01mzML-ms2Summary.xlsx

    Output:
        SamplesNames:
            list of sample names after removing ToReplace.
    """

    SamplesList = [x for x in os.listdir(ResultsFolder)
                   if x.lower().endswith(".xlsx") and not x.startswith(".")]

    SamplesList.sort()

    SamplesNames = []

    for features_table in SamplesList:
        sample_name = features_table.replace(ToReplace,
                                             "")

        SamplesNames.append(sample_name)

    return SamplesNames
